apiVersion: apps/v1
kind: Deployment
metadata:
  name: gfth6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gfth6
  template:
    metadata:
      labels:
        app: gfth6
    spec:
      containers:
      - image: okteto.dev/gfth6:latest
        name: gfth6
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "ed82c074-5daf-44aa-a25c-d1d902a8d86d"
        - name: Vless_Path
          value: "/sddrvgfhbgr"
        - name: Vmess_UUID
          value: "ed82c074-5daf-44aa-a25c-d1d902a8d86d"
        - name: Vmess_Path
          value: "/vfdhyhthu7"
        - name: Share_Path
          value: "/v2link"
