apiVersion: v1
kind: Service
metadata:
  name: gfth6
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "gfth6"
    port: 8080
  selector:
    app: gfth6
